workflows:
  neno-ios:
    name: Neno iOS
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Generate launcher icons
        script: dart run flutter_launcher_icons
      - name: Run tests
        script: flutter test
      - name: Build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign --export-options-plist $CM_BUILD_DIR/ExportOptions.plist
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Beta Testers
